---
title: "Evaluation of Forest Ecosystem Services"
author: "M. De Cáceres, J.V. Roces Diaz, J. Martinez-Vilalta, J. Vayreda, M. Banqué,
  F. D’Adamo, J.M. Espelta"
date: "2023-07-07"
output:
  html_document: default
  pdf_document: default
  word_document: default
bibliography: references.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction

This technical document provides the definition and operational estimation procedures of a number of forest ecosystem services to be evaluated for Catalonia (NE Spain) both in historical assessments (using forest inventory data) and future projections (using model simulations of forest function and dynamics). 

The following table, modified from @roces-diaz_assessing_2018, provides a summary of  definitions and indicators included:

|  Category  | Forest ecosystem service | Indicator    | Definition                           |
|------------|--------------------------|--------------|--------------------------------------|
| Provisioning | Provision of raw materials | Timber and firewood | Timber and firewood harvesting in public and private forests per year |
| Provisioning | Food provision | Mushroom production | Edible mushroom production for pine, oak and fir forests per year |
| Provisioning | Water provision | Blue water | Water exported by surface runoff or deep drainage into the water table |
| Provisioning | Water provision | Runoff coefficient | Ratio of blue water over precipitation |
| Regulating | Climate regulation | Forest carbon sink | Forest carbon in above-ground and below-ground woody tissues of vegetation |
| Regulating | Water regulation | Vegetation and soil water storage capacity | Sum of vegetation water storage capacity and soil water holding capacity of the forest stand |
| Regulating | Erosion control | Erosion control | Amount of rainfall erosive potential that is mitigated due to vegetation cover |
| Cultural | Recreational | Recreational value | The perception of the value of the forest stand for recreational purposes as a function of its structure and composition |
| Cultural | Biodiversity potential | Biodiversity Potential Index | Potential of the forest stand to serve as habitat for biodiversity, on the basis of its vertical structure, diversity of woody species and presence of dead wood and large trees |

The next sections detail the metrics and estimation procedures of each ecosystem service. 

## Provision services

### Provision of materials

**Indicator**: Timber and firewood

**Definition**: Timber and firewood harvested in forest stands per year

**Metric and units**: $m^3 \cdot ha^{-1} \cdot yr^{-1}$ of timber and firewood

**Estimation procedures**: For historic periods, observed harvesting can be obtained from forestry statistics of the target area. In addition, tree cuts between forest inventories in permanent plots can also be used to estimate harvested wood. For future projections, simulations of forest dynamics including management scenarios are also possible. Whatever the source of harvesting information, a distinction is made between timber (wood for construction) and firewood, on the basis of tree diameter at breast height (DBH) and species: 

  + *Timber*: Trees from all species, except holm oak (*Quercus ilex*), and DBH > 22.5
  + *Firewood*: Trees of holm oak (*Quercus ilex*), with DBH > 7.5, or trees of other species and 7.5 < DBH < 22.5

The volume ($m^3 \cdot ha^{-1}$) of each product is obtained applying allometric volume equations depending on species, DBH and height, which are provided by the Spanish National Forest Inventory for each Spanish province and survey (in the case of future projections, equations from IFN3 are used). The volume corresponding to a given tree is multiplied by the density factor to obtain the volume per hectare and values are aggregated across tree records. Function `IFNvolume()` from the R package called `IFNallometry` (available at GitHub) is used for volume calculations.

**Potential improvements**: The distinction among products could be made more sophisticated by considering a table indicating the proportion of different products for combinations of species and DBH class.

### Food provision

**Indicator**: Mushroom production

**Definition**:  Edible mushroom production for pine, oak and fir forests per year

**Metric and units**: Annual production of edible mushrooms, $kg^{-1} \cdot ha^{-1} \cdot yr^{-1}$

**Estimation procedures**: Empirical models have been developed for edible mushrooms in Catalan pine forests by de Miguel et al [-@de-miguel_impact_2014].

**Potential improvements**: Need to include direct climate influences on mushroom production as well as models including other forest types.

### Water provision (1)

**Indicator**: Blue water

**Definition**: Water exported by surface runoff or deep drainage into the water table per year

**Metric and units**: $mm \cdot yr^{-1} = l \cdot m^2\cdot yr^{-1}$

**Estimation procedures**:

Blue water is defined as the sum of water leaving the forest stand via overland (surface) runoff and the water draining beyond the reach of plant roots (i.e. deep drainage). These two flows can be estimated on a daily scale using a water balance model, and then be aggregated for period of evaluation and expressed as $mm \cdot yr^{-1}$. In our case, the MEDFATE model [@DeCaceres2015] is used for performing water balance simulations over the evaluation period (see model details in ). 

**Remarks and potential improvements**: This indicator is appropriate to estimate the forest disservice of water supply, in absolute terms, but is very sensitive on the precipitation occurred during the evaluation period.

### Water provision (2)

**Indicator**: Runoff ratio

**Definition**: Ratio of blue water over precipitation for an evaluation period

**Metric and units**: A coefficient ranging between 0 (no water is exported) and 1 (all water that falls in the stand becomes blue water)

**Estimation procedures**:

This indicator is estimated from the previous one, dividing the amount of blue water estimated for the evaluation period by the amount of precipitation in the same period.

**Remarks and potential improvements**: Even though this indicator is defined as a ratio, it is still dependent on the weather data used for evaluation. Generally speaking, the longer the period of evaluation (e.g. 5-10 years minimum) the more will the indicator reflect the role of forest structure and composition on provision, because variation in the run-off coefficient caused by inter-annual variation in precipitation will tend to be smoothed out.

## Regulation services


### Climate regulation

**Indicator**: Forest carbon sink

**Definition**: Forest carbon sink in above-ground and below-ground woody tissues of vegetation

**Metric and units**: $Mg\,\,CO_2 \cdot ha^{-1} \cdot yr^{-1}$ or $Mg\,\,C \cdot ha^{-1} \cdot yr^{-1}$

**Estimation procedures**: For historic periods, carbon sink can be obtained comparing wood biomass estimates from permanent plots of forest inventories. For future projections, simulations of forest dynamics are also possible. The sink rate is estimated subtracting the wood biomass at the beginning of the evaluation period from the wood biomass estimate at the end of the evaluation period. It is possible to consider the biomass extracted in forest management as additional source of forest growth that is not observed when comparing the biomass estimates of standing trees. The tree biomass ($Mg CO_2^3 \cdot ha^{-1}$) is obtained applying allometric biomass equations for the above-ground and below-ground components, which depend on DBH and height and where published in [refs]. Function `IFNbiomass()` from the R package called `IFNallometry` (available at GitHub) is used for biomass calculations.

**Remarks and potential improvements**:


### Water regulation

**Indicator**: Vegetation and soil water storage capacity

**Definition**: Sum of vegetation water storage capacity and soil water holding capacity of the forest stand

**Metric and units**: mm = l/m2 of water that can be held in the canopy and soil

**Estimation procedures**:

The indicator for water regulation service of a forest stand has been defined as the sum of vegetation ($C_m$) and soil water storage capacity:

$$WR = C_m + \sum_s{V_{fc,s}}$$

*Vegetation water holding capacity* is estimated from the leaf area index of herbs and woody plant cohorts in the forest stand [@Watanabe1996]:
$$C_m = LAI_{herb}\cdot S_{herb} + \sum_i{ LAI_i \cdot S_i}$$
where $LAI_{herb}$ is the leaf area index of the herbaceous layer, $S_{herb} = 1$ is the water holding capacity per LAI unit of the herbaceous layer, $LAI_i$ is the leaf area index of plant woody cohort $i$ and $S_i$ is the water-holding capacity per LAI unit of woody cohort $i$, which depends on species identity. 

*Soil water holding capacity* is estimated as the sum, over all $s$ soil layers, of the volume that can be held given soil layer depth $d_s$, texture and percentage of rocks $P_{rocks,s}$:
$$V_{fc,s} = d_s\cdot ((100-P_{rocks,s})/100)\cdot\theta_{fc,s}$$
where $\theta_{fc,s}$ is the soil moisture content of the soil layer at field capacity (i.e. at -0.033 MPa), which depends on soil texture and organic matter content. $\theta_{fc,s}$ is estimated from texture, bulk density and organic matter using Saxton & Rawls [-@Saxton2006]'s pedotransfer functions. Calculations are conducted using function `soil_waterFC()` from package **medfate**.

**Remarks and potential improvements**: Of the two components, only $C_m$ is dynamic. Moreover, the estimation of $V_{fc,s}$ is very uncertain unless reliable information is available on $P_{rocks,s}$. The water regulation service could be estimated as the ratio between deep drainage flow and the overall water exported from the stand, assuming that sub-surface flows are better than surface flows from the perspective of hydrological regulation.



### Erosion control

**Indicator**: Erosion control

**Definition**: Amount of rainfall erosive potential that is mitigated due to vegetation cover

**Metric and units**: $Mg \cdot ha^{-1} \cdot yr^{-1}$

**Estimation procedures**: The estimation procedure is similar to to Guerra et al. [-@guerra_assessment_2016], who re-interpreted the classical Revised Universal Soil Loss Equation (RUSLE), and Morán-Ordóñez et al. [-@moranordonez_future_2020]. The RUSLE method estimates soil erosion as the product of $K \cdot LS \cdot R \cdot C \cdot P$, where $K$ is soil erodibility (an intrinsic characteristic of each soil type), $LS$ is the topographic factor accounting for the slope length and steepness, $R$ is a non-dimensional factor of physical erosivity of rainfall, $C$ is related with the type and structure of the vegetation of each stand and finally $P$ is the conservation practices factor (not considered here). 

For our calculations, we first estimate for the evaluation period the structural impact ($\gamma$), i.e. potential soil erosion if vegetation were absent:
  $$\gamma = K \cdot LS \cdot R$$
and the estimated actual soil loss $\beta$ after vegetation cover is considered:

$$ \beta = K \cdot LS \cdot R \cdot C $$, 

and finally calculated the erosion mitigation (mitigated impact) as their difference:

$$EM = \gamma - \beta = K \cdot LS \cdot R \cdot (1 - C)$$
Erosion components are estimated as follows:

 + $K$ values were sourced from the data base by Panagos et al. (2014) at 500 m resolution; 
 + $LS$ were obtained at 25 m of resolution from Panagos et al. (2015). 
 + $R$ is calculated using the model by Diodato and Bellocchi [-@diodato_medrem_2010] and daily rainfall data (from “meteoland” package, De Caceres et al., 2018).
 + $C$ is the mitigation (reduction) effect of vegetation cover. Despite the $C$ term promotes its interpretation as cover, a complete vegetation cover should have a maximum reduction of erosion, and hence $C = 0$. In practice, we estimate $C$ as the faction of photosynthetically active radiation (PAR) reaching the ground ($FPAR_{ground}$), which can be estimated as a function of leaf area index and extinction coefficients:
 $$C = FPAR_{ground}=e^{-0.5 \cdot LAI_{herb}} \cdot e^{-\sum_{i}{k_{i} \cdot LAI_{i}}}$$
where $LAI_{herb}$ is the leaf area index of herbaceous vegetation (when present), $LAI_i$ is the leaf area index of woody cohort $i$, $k_i$ is the corresponding extinction coefficient for PAR.

**Potential improvements**:

## Cultural services

### Recreational

**Indicator**: Recreational value

**Definition**: The perception of the value of the forest stand for recreational purposes as a function of its structure and composition

**Metric and units**: A value between 0 (no recreational value) and 1 (maximum recreational value).

**Estimation procedures** (yet to be implemented in a function):

A literature review allowed us to identify a number of key studies relating vegetation structure and composition to the potential recreational value of forests. From these papers, we extracted only those metrics that we believe can be estimated from standard dynamic model outputs. These are five stand-level metrics, i.e., tree size, variation in tree size, thickness of vegetation cover, density of ground vegetation, number of tree and shrub species, and two landscape-level metrics, i.e., variation between stands (landscape variability) and uniqueness (areas with the lowest density of plots have higher uniqueness).

| Definition              |  Level | Metric           |  Range      |
|-------------------------|--------|------------------|-------------|
| Tree size               | Stand  | Maximum DBH      | ca. 0 - 100 |
| Variation in tree size  | Stand  | CV DBH           | 0 - 1.5     |
| Thickness of vegetation cover | Stand | LAI (trees + shrubs) | ca. 0 - 8 |
| Density of ground vegetation | Stand | Maximum shrub cover | 1 - 90 |
| Number of tree and shrub species | Stand | Woody plant species richness (trees + shrubs) | 1 - 30 |
| Variation of tree size between stands | Landscape | CV of average DBH relative to the nearby stands | 0 - 1 |
| Uniqueness | Landscape | 1 – proportion of forest cover relative to the nearby stands | 0 - 1 |


Keeping in mind the model output related to each metric and its range value in the Catalan forest, we will present our participants with a questionnaire where we ask them to simply draw what they think is the shape of the function that best relates each model output to the potential recreational value, scored between 0 and 1. Each questionnaire respondent produces a potential recreational value between 0 and 1 for each of the seven model metrics (i.e., 5 stand-level and 2 landscape-level). We allow four types of relationships, i.e., linear increase, linear decline, V-shaped relationship, and inverted V-shaped relationship. The answers of the questionnaire respondents should be aggregated for each metric into a single function. Then, the seven different functions should combined into an overall potential recreational value. One possibility is to ask the importance of the different metrics in the same questionnaire and average the answers to estimate weights.

**Potential improvements**: The idea was to include also the amount of natural deadwood, but then the index becomes conceptually closer to the biodiversity potential. In projections of forest dynamics, inclusion of species richness into this indicator requires that the model incorporates colonization processes. Otherwise, local extinction will always decrease species richness.


### Biodiversity potential

**Indicator**: Biodiversity potential index (BPI)

**Definition**: Potential of the forest stand to serve as habitat for biodiversity, on the basis of its vertical structure, diversity of woody species and presence of dead wood and large trees.

**Metric and units**: A value between 0 (lowest biodiversity potential) and 5 (highest biodiversity potential).

**Estimation procedures**  (yet to be implemented in a function):

The *Index de Biodiversitat Potencial* (IBP) was adapted to Catalonia region by *Centre de la Propietat Forestal* [@baiges_teresa_posada_2019] from the work by @larrieu_lindice_2008. IBP was designed to be applied in the field and, therefore, not all its ten components can be evaluated from model simulation results. Here we adapted the Catalan IBP focusing on the following four components: 

  A) Diversity of native (or archaeophyte) species
  B) Vertical structure of vegetation
  C) The presence of dead wood
  D) The presence of large dead trees

Moreover the current application of IBP in Catalonia (IBP ver. 3) is slightly different depending on two spatial domains: (D1) Mediterranean domain; (D2) Montane-subalpine domain. We addressed this level of complexity by calculating our BPI twice, once assuming one domain or the other, followed by averaging the two resulting values with weights depending on the ascription of the tree species occurring in the stand to the two domains. The following describes how the A-D components are estimated for each of the two domains and how the final BPI value is determined.

*$BPI_A$ - Native species*

This component evaluates the diversity of native (or archaeophyte) tree species with individuals taller than 50 cm height in the stand. The list of native genus/species is the following: *Quercus*, *Arbutus*, *Cercis*, *Acer*, *Corylus*, *Abies*, *Betula*, *Castanea*, *Prunus avium*, *Pinus*, *Fagus sylvatica*, *Fraxinus*, *Ceratonia*, *Celtis*, *Juglans regia*, *Olea europaea*, *Ulmus*, *Pyrus*, *Malus*, *Populus alba*, *Juniperus thurifera*, *Salix*, *Sorbus*, *Taxus*, *Tilia*, *Alnus*, *Cupressus*
 
The following table describes how component $BPI_A$ is defined depending on the number of genus of native species present in the stand and the domain of application:

| $BPI_A$ value | Criterion D1 | Criterion D2 |
|---------|-----------|-----------|
|  0  |  0 or 1 genus  | 0 or 1 genus |
|  1  |  2 genus | 2 genus  |
|  2  |  3 or 4 genus | 3 genus |
|  5  |  5 or more genus | 4 or more genus |

For D2 we simplified the two tables in BPI. If the cover sum of native (or archaephyte) species is less than 50%, then A cannot be larger than 2.

*$BPI_B$ - Vertical structure of vegetation*

Calculate the cover of each cohort (for shrubs is directly in the shrub data, for trees it comes from allometry based DBH and open assumption). Classify cohorts into strata according to their height. Sum the total cover of each strata. Count the number of strata that are more than 20% cover.

| $BPI_B$ value | Criterion |
|---------|-----------|
| 0 | 0 or 1 stratum with > 20% cover |
| 1 | 2 strata with > 20% cover |
| 2 | 3 or 4 strata > 20% cover |
| 5 | 5 or more strata > 20% cover |

*$BPI_C$ - Dead wood* 

Here we do not distinguishing between standing dead trees (i.e. snags) and dead trees in the ground (i.e. logs). Moreover, it is assumed that decay (decomposition) of dead wood is dealt externally, so that the index is calculated considering the actual current amount of dead wood in the stand. 

First, dead trees are classified into medium or large depending on their size and domain of application:

 + For D1, classify dead trees as *medium dead wood (MDW)* if 17.5 < DBH < 27.5 or *large dead wood (LDW)* if DBH > 27.5
 + For D2, classify dead trees as *medium dead wood (MDW)* if 17.5 < DBH < 37.5 or *large dead wood (LDW)* if DBH > 37.5
 + Regardless of the domain, if species has a slow growth (Alnus, Arbutus, Acer, Pyrus, Malus, Sorbus) then if DBH > 17.5 cm is already considered as LDW

Then, the value of dead wood component is determined from the density of dead trees in MDW and LDW classes, using the following table:

| $BPI_C$ value | Criterion |
|---------|-----------|
| 0 | 1 < LDW/ha & 1 < MDW/ha |
| 1 | 1 < LDW/ha & 1 >= MDW/ha |
| 2 | 1 to 3 LDW/ha |
| 5 | More than 3 LDW/ha |

*$BPI_D$ - Large trees alive*

First, live trees are classified into large or very large depending on their size and domain of application:

  + For D1, classify trees as *large trees (LT)* if 37.5 cm < DBH < 57.5 cm or *very large trees (VLT)* if > 57.5 cm.
  + For D2, classify trees as *large trees (LT)* if 47.5 cm < DBH < 67.5 cm or *very large trees (VLT)* if > 67.5 cm.
  + Regardless of the domain, if species has a slow growth (Alnus, Arbutus, Acer, Pyrus, Malus, Sorbus) then if DBH > 37.5 cm is already considered as VLT.
  
Then, the value of large trees is determined from the density of trees in LT and VLT classes, using the following table:

| $BPI_D$ value | Criterion |
|---------|-----------|
| 0 | 1 < VLT/ha & 1 < LT/ha |
| 1 | 1 < VLT/ha & 1 >= LT/ha |
| 2 | 1 to 5 VTL/ha |
| 5 | More than 5 VTL/ha |

*Overall Biodiversity Potential Index*

BPI is the average of the four metrics, each one going from 0 to 5. Double weight is given to dead wood, according to the original definition of considering snags and logs separately.

$$BPI_{domain} = (BPI_A + BPI_B + 2 \cdot BPI_C + BPI_D)/5$$
For a given plot, we calculate BPI corresponding to each of the two domains, i.e. $BPI_{D1}$ and $BPI_{D2}$.  Then, we perform a weighted average of the two BPI values using the sum of basal area of species belonging to each of the domains, $BA_{D1}$ and $BA_{D2}$ as weights:

$$BPI = \frac{BPI_{D1} \cdot BA_{D1} + BPI_{D2} \cdot BA_{D2}}{BA_{D1} + BA_{D2}}$$

**Potential improvements**: In projections of forest dynamics, inclusion of species richness into this indicator requires that the model incorporates colonization processes. Otherwise, local extinction will always decrease species richness.

## References
